# Generated by Django 5.1.2 on 2024-10-10 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mehmonxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('yulduzlar_soni', models.PositiveIntegerField()),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Travle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('izoh', models.TextField()),
                ('muddati', models.PositiveIntegerField(help_text='Sayohat davomiyligi (kunlarda)')),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.klass')),
                ('mehmonxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.mehmonxona')),
            ],
        ),
    ]
